# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MindMeld

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        mm-extras: ["false"] # Extras are all broken for now
        es_version: [ "7.17.28" ]

    steps:
    - uses: actions/checkout@v4

    - uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: ${{ matrix.es_version }}
        security-enabled: false
        plugins: "analysis-phonetic"
        elasticsearch_password: ${{ secrets.ELASTIC_SECRET }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        #java-version: '9.0.4' # The JDK version to make available on the path.
        #java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
      env:
        MM_EXTRAS: ${{ matrix.mm-extras }}

    - name: Install dependencies
      run: |
        ./scripts/py_dep_install.sh
      env:
        MM_EXTRAS: ${{ matrix.mm-extras }}

    - name: Linting
      continue-on-error: true
      run: |
        ./lintme

    - name: Running numerical parser
      uses: addnab/docker-run-action@v3
      with:
        image: mindmeldworkbench/duckling:master
        options: -ti -d -p 0.0.0.0:7151:7151

    #- name: Running numerical parser
    #  run: |
    #    python3 -m mindmeld.cli num-parse

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Test with pytest
      # We want to upload test results whether they pass or not
      continue-on-error: true
      run: |
        mkdir ~/test-reports
        pytest --junitxml=~/test-results/junit-${{ matrix.python-version }}-${{ matrix.mm-extras }}.xml --cov-report html --cov=mindmeld --ignore=examples/
      env:
        MM_ES_HOST: es1
        MM_EXTRAS: ${{ matrix.mm-extras }}
        MM_SUBPROCESS_COUNT: 0

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      with:
        report_paths: '~/test-results/junit-${{ matrix.python-version }}-${{ matrix.mm-extras }}.xml'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: junitxml
        path: '~/test-results/junit-${{ matrix.python-version }}-${{ matrix.mm-extras }}.xml'
